export default {
    // Base URL of the website you're scraping (informational only)
    BASE_URL: "https://phxinjurylaw.com",

    // List of URLs to scrape
    URLS: [
        "https://phxinjurylaw.com/blog/motorcycle-accidents-during-arizonas-tourism-season-what-riders-need-to-know/",
        "https://phxinjurylaw.com/blog/how-major-insurance-companies-exploit-accident-victims-in-arizona/",
        "https://phxinjurylaw.com/blog/navigating-family-disputes-in-wrongful-death-cases/",
        "https://phxinjurylaw.com/blog/pedestrian-wrongful-death-cases/",
        "https://phxinjurylaw.com/blog/how-wrongful-death-settlements-work-in-arizona/",
        "https://phxinjurylaw.com/blog/why-cement-truck-accidents-cause-catastrophic-injuries/",
        "https://phxinjurylaw.com/blog/why-uber-and-lyft-drivers-face-higher-accident-risks-in-phoenix/",
        "https://phxinjurylaw.com/blog/insurance-coverage-gaps-that-leave-uber-and-lyft-drivers-vulnerable/",
        "https://phxinjurylaw.com/blog/child-injured-in-school-bus-accident/",
        "https://phxinjurylaw.com/blog/hit-and-run-accidents-in-phoenix/",
        "https://phxinjurylaw.com/blog/can-i-sue-if-i-was-a-passenger/",
        "https://phxinjurylaw.com/blog/the-true-cost-of-a-dui-in-arizona/",
        "https://phxinjurylaw.com/blog/pedestrian-safety-in-phoenix-your/",
        "https://phxinjurylaw.com/blog/the-hidden-costs-of-catastrophic-injuries-beyond-medical-bills/",
        "https://phxinjurylaw.com/blog/why-most-personal-injury-cases-never-make-it-to-trial/",
        "https://phxinjurylaw.com/blog/filing-a-wrongful-death-claim-in-arizona/",
        "https://phxinjurylaw.com/blog/what-happens-at-a-victim-impact-hearing-in-arizona/",
        "https://phxinjurylaw.com/blog/the-problem-with-phoenix-roads/",
        "https://phxinjurylaw.com/blog/scooter-accidents-are-skyrocketing-phoenix/",
        "https://phxinjurylaw.com/blog/pedestrian-accidents-in-phoenix-why-are-fatalities-increasing/",
        "https://phxinjurylaw.com/blog/chiropractor-personal-injury-case/",
        "https://phxinjurylaw.com/blog/scooters-duis-and-liability-in-arizona/",
        "https://phxinjurylaw.com/blog/who-can-file-a-wrongful-death-claim/",
        "https://phxinjurylaw.com/blog/the-legal-impact-of-delayed-injuries/",
        "https://phxinjurylaw.com/blog/your-guide-to-arizona-child-seat-and-front-seat-laws/",
        "https://phxinjurylaw.com/blog/what-insurance-adjusters-can-legally-do/",
        "https://phxinjurylaw.com/blog/dont-need-a-personal-injury-lawyer-if-you-have-insurance-false/",
        "https://phxinjurylaw.com/blog/hit-in-a-crosswalk-driver-claimed-no-fault/",
        "https://phxinjurylaw.com/blog/your-rights-after-a-car-accident-in-arizona/",
        "https://phxinjurylaw.com/blog/phoenix-bone-fracture-lawyer/",
        "https://phxinjurylaw.com/blog/whiplash-from-rear-end-collision/",
        "https://phxinjurylaw.com/blog/rear-end-accidents-lawyers/",
        "https://phxinjurylaw.com/blog/minor-car-accident-lawyer/",
        "https://phxinjurylaw.com/blog/red-light-lawyer/",
        "https://phxinjurylaw.com/blog/neck-injury-lawyer-in-arizona/",
        "https://phxinjurylaw.com/blog/back-injury-lawyers/",
        "https://phxinjurylaw.com/blog/head-on-collision-lawyer-arizona/",
        "https://phxinjurylaw.com/blog/t-bone-car-crash-lawyers-arizona/",
        "https://phxinjurylaw.com/blog/teenager-car-accident-lawyers-arizona/",
        "https://phxinjurylaw.com/blog/wrong-way-driving-accident-lawyers-arizona/",
        "https://phxinjurylaw.com/blog/phoenix-brain-injury-lawyers/",
        "https://phxinjurylaw.com/blog/total-loss-lawyer-in-arizona/",
        "https://phxinjurylaw.com/blog/hit-and-run-lawyer-in-arizona/",
        "https://phxinjurylaw.com/blog/lyft-uber-accident-lawyer-in-phoenix/",
        "https://phxinjurylaw.com/blog/left-turn-accident-lawyers/",
        "https://phxinjurylaw.com/blog/53-auto-accident-faqs/",
        "https://phxinjurylaw.com/blog/insurance-payout-for-totaled-car/",
        "https://phxinjurylaw.com/blog/t-bone-car-accident-injuries/",
        "https://phxinjurylaw.com/blog/wrongful-death-lawsuit-attorney/",
        "https://phxinjurylaw.com/blog/neck-injuries-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/uninsured-or-underinsured-driver-in-arizona/",
        "https://phxinjurylaw.com/blog/considered-negligent-in-arizona/",
        "https://phxinjurylaw.com/blog/5-sneaky-tactics-of-insurance-companies/",
        "https://phxinjurylaw.com/blog/arizona-bicycle-helmet-laws/",
        "https://phxinjurylaw.com/blog/dram-shop-claim-liability/",
        "https://phxinjurylaw.com/blog/what-are-medical-liens/",
        "https://phxinjurylaw.com/blog/fix-car-with-insurance-money/",
        "https://phxinjurylaw.com/blog/left-hand-turn-collision/",
        "https://phxinjurylaw.com/blog/car-rental-reimbursement-after-accident/",
        "https://phxinjurylaw.com/blog/arizona-punitive-damages-wrongful-death/",
        "https://phxinjurylaw.com/blog/soft-tissue-injury-settlement-auto-accident/",
        "https://phxinjurylaw.com/blog/what-to-do-when-someone-hits-your-parked-car/",
        "https://phxinjurylaw.com/blog/auto-accident-loans-after-incident/",
        "https://phxinjurylaw.com/blog/az-open-container-law/",
        "https://phxinjurylaw.com/blog/over-serving-alcohol-law/",
        "https://phxinjurylaw.com/blog/arizonas-laws-for-bicycle-accident-cases/",
        "https://phxinjurylaw.com/blog/handle-your-own-auto-accident-claim/",
        "https://phxinjurylaw.com/blog/secure-rear-end-collision-settlement/",
        "https://phxinjurylaw.com/blog/reason-to-seek-car-accident-doctor/",
        "https://phxinjurylaw.com/blog/internal-injuries-after-car-accident/",
        "https://phxinjurylaw.com/blog/the-process-of-an-auto-accident-lawsuit/",
        "https://phxinjurylaw.com/blog/rear-end-collision/",
        "https://phxinjurylaw.com/blog/fatal-car-accident-settlement/",
        "https://phxinjurylaw.com/blog/arizona-bicycle-laws/",
        "https://phxinjurylaw.com/blog/pain-and-suffering-settlement/",
        "https://phxinjurylaw.com/blog/arizona-open-container-laws/",
        "https://phxinjurylaw.com/blog/lost-wages-vs-lost-earning-capacity/",
        "https://phxinjurylaw.com/blog/doctor-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/average-bus-accident-lawsuit-settlement/",
        "https://phxinjurylaw.com/blog/soft-tissue-injury-after-car-accident/",
        "https://phxinjurylaw.com/blog/lost-wage-claim-car-accident/",
        "https://phxinjurylaw.com/blog/arizona-wrongful-death-statute/",
        "https://phxinjurylaw.com/blog/car-accident-loans-in-arizona/",
        "https://phxinjurylaw.com/blog/blood-alcohol-content-level-in-arizona-law/",
        "https://phxinjurylaw.com/blog/therapy-after-car-accident/",
        "https://phxinjurylaw.com/blog/are-personal-injury-settlements-taxable/",
        "https://phxinjurylaw.com/blog/sneaky-marketing-tactics-insurance-companies/",
        "https://phxinjurylaw.com/blog/who-gets-the-insurance-check-car-is-totaled/",
        "https://phxinjurylaw.com/blog/how-to-scare-an-insurance-adjuster/",
        "https://phxinjurylaw.com/blog/7-bike-safety-tips-you-cant-afford-to-ignore/",
        "https://phxinjurylaw.com/blog/fatal-car-crash-settlement/",
        "https://phxinjurylaw.com/blog/how-to-read-a-police-report-car-accident/",
        "https://phxinjurylaw.com/blog/settle-your-truck-accident-claim/",
        "https://phxinjurylaw.com/blog/the-truth-about-trucker-regulations/",
        "https://phxinjurylaw.com/blog/commercial-truck-accidents-important-facts/",
        "https://phxinjurylaw.com/blog/car-accidents-in-phoenix/",
        "https://phxinjurylaw.com/blog/medical-payments-insurance-in-arizona/",
        "https://phxinjurylaw.com/blog/rights-of-victims-of-dui-accidents/",
        "https://phxinjurylaw.com/blog/arizona-constitutional-rights-for-crime-victims/",
        "https://phxinjurylaw.com/blog/how-to-claim-damages-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/negligence-car-accident/",
        "https://phxinjurylaw.com/blog/best-arizona-bus-accident-attorney/",
        "https://phxinjurylaw.com/blog/wrong-way-drivers-101/",
        "https://phxinjurylaw.com/blog/car-accident-while-pregnant/",
        "https://phxinjurylaw.com/blog/auto-accident-faqs/",
        "https://phxinjurylaw.com/blog/auto-accident-article-hub/",
        "https://phxinjurylaw.com/blog/punitive-damages-dui/",
        "https://phxinjurylaw.com/blog/pre-existing-conditions-law/",
        "https://phxinjurylaw.com/blog/average-car-accident-settlement-arizona/",
        "https://phxinjurylaw.com/blog/personal-injury-damage-awards/",
        "https://phxinjurylaw.com/blog/pain-and-suffering-after-accident/",
        "https://phxinjurylaw.com/blog/auto-accident-insurance-coverage/",
        "https://phxinjurylaw.com/blog/how-long-does-a-personal-injury-lawsuit-take/",
        "https://phxinjurylaw.com/blog/your-rights-after-an-uber-accident/",
        "https://phxinjurylaw.com/blog/auto-accidents-in-chandler-arizona/",
        "https://phxinjurylaw.com/blog/automobile-and-bicycle-accident/",
        "https://phxinjurylaw.com/blog/dui-justice-process/",
        "https://phxinjurylaw.com/blog/dui-accident-lawyers-in-arizona/",
        "https://phxinjurylaw.com/blog/miscarriage-after-car-accident/",
        "https://phxinjurylaw.com/blog/arm-and-leg-injuries-in-car-accident/",
        "https://phxinjurylaw.com/blog/lost-wages-claim-sick-vacation-leave/",
        "https://phxinjurylaw.com/blog/brain-injury-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/car-accident-on-the-freeway/",
        "https://phxinjurylaw.com/blog/arizona-car-accident-laws-leg-arm-injury-claim/",
        "https://phxinjurylaw.com/blog/medical-treatment-after-car-accident/",
        "https://phxinjurylaw.com/blog/personal-injury-claim-after-car-accident/",
        "https://phxinjurylaw.com/blog/hit-and-run-accidents-in-arizona/",
        "https://phxinjurylaw.com/blog/back-injuries-in-auto-accidents-2/",
        "https://phxinjurylaw.com/blog/distracted-driving-accidents/",
        "https://phxinjurylaw.com/blog/fee-splitting-in-arizona/",
        "https://phxinjurylaw.com/blog/manufacturing-defect-causes-accident/",
        "https://phxinjurylaw.com/blog/semi-truck-safety-equipment-for-safer-travel/",
        "https://phxinjurylaw.com/blog/emotional-recovery-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/coping-with-back-pain-after-auto-accident/",
        "https://phxinjurylaw.com/blog/settling-an-injury-lawsuit-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/choosing-right-personal-injury-lawyer/",
        "https://phxinjurylaw.com/blog/miscarriage-after-a-motor-accident/",
        "https://phxinjurylaw.com/blog/car-accident-negligence/",
        "https://phxinjurylaw.com/blog/seatbelts-in-car-accident-and-your-claim/",
        "https://phxinjurylaw.com/blog/civil-justice-process-for-dui-victims/",
        "https://phxinjurylaw.com/blog/arizona-car-accident-injuries/",
        "https://phxinjurylaw.com/blog/manufacturing-defect-car-accidents/",
        "https://phxinjurylaw.com/blog/calculating-damages-in-personal-injury-cases/",
        "https://phxinjurylaw.com/blog/whiplash-and-knee-injury-in-a-car-accident/",
        "https://phxinjurylaw.com/blog/courtroom-testimony-tips/",
        "https://phxinjurylaw.com/blog/high-speed-car-crash/",
        "https://phxinjurylaw.com/blog/what-not-to-say-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/distracted-drivers-awareness-month-2020/",
        "https://phxinjurylaw.com/blog/medical-treatment-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/hit-and-run-victims-law-in-arizona/",
        "https://phxinjurylaw.com/blog/chameleon-trucking-companies-issue/",
        "https://phxinjurylaw.com/blog/recovery-path-of-drunk-driving-victims/",
        "https://phxinjurylaw.com/blog/most-common-injuries-in-a-car-accident/",
        "https://phxinjurylaw.com/blog/taxes-on-wrongful-death-settlements/",
        "https://phxinjurylaw.com/blog/hit-and-run-intersection-accident/",
        "https://phxinjurylaw.com/blog/bicycle-safety-in-arizona/",
        "https://phxinjurylaw.com/blog/right-compensation-payouts-in-car-accident/",
        "https://phxinjurylaw.com/blog/10-things-about-bus-accidents-in-arizona/",
        "https://phxinjurylaw.com/blog/car-accident-in-arizona-not-your-fault/",
        "https://phxinjurylaw.com/blog/high-speed-hit-and-run-crash/",
        "https://phxinjurylaw.com/blog/rear-end-car-accident-stop-sign/",
        "https://phxinjurylaw.com/blog/soft-tissue-damage-after-car-accident/",
        "https://phxinjurylaw.com/blog/personal-injury-lawyer-questions/",
        "https://phxinjurylaw.com/blog/bicycle-safety-rules-in-arizona/",
        "https://phxinjurylaw.com/blog/medical-care-car-accident-guide/",
        "https://phxinjurylaw.com/blog/back-injury-after-an-auto-accident/",
        "https://phxinjurylaw.com/blog/sleep-apnea-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/dram-shop-liability-law/",
        "https://phxinjurylaw.com/blog/arizona-dui-law-civil-lawsuits/",
        "https://phxinjurylaw.com/blog/senate-to-suspend-truck-driver-safety-rules/",
        "https://phxinjurylaw.com/blog/dui-and-the-dram-shop-laws/",
        "https://phxinjurylaw.com/blog/car-accident-injuries-in-arizona/",
        "https://phxinjurylaw.com/blog/how-to-deal-with-a-dui-emotionally/",
        "https://phxinjurylaw.com/blog/what-is-distracted-driving-arizona/",
        "https://phxinjurylaw.com/blog/fair-compensation-after-car-accident/",
        "https://phxinjurylaw.com/blog/car-accident-settlement-process/",
        "https://phxinjurylaw.com/blog/car-accident-property-damage-claim/",
        "https://phxinjurylaw.com/blog/average-settlement-for-rear-end-collision/",
        "https://phxinjurylaw.com/blog/restitution-for-dui-accident/",
        "https://phxinjurylaw.com/blog/impaired-driving-bicycle-accident-case/",
        "https://phxinjurylaw.com/blog/file-a-personal-injury-insurance-claim/",
        "https://phxinjurylaw.com/blog/drugged-driving-car-accidents/",
        "https://phxinjurylaw.com/blog/insurance-claims-for-car-accident/",
        "https://phxinjurylaw.com/blog/broken-bones-in-a-car-accident/",
        "https://phxinjurylaw.com/blog/partially-at-fault-in-a-bicycle-accident/",
        "https://phxinjurylaw.com/blog/personal-damages-case-worth/",
        "https://phxinjurylaw.com/blog/car-accident-property-damage-settlement/",
        "https://phxinjurylaw.com/blog/pain-and-suffering-after-car-accident-mean/",
        "https://phxinjurylaw.com/blog/proving-fault-in-a-car-accident/",
        "https://phxinjurylaw.com/blog/drunk-buzzed-driving-accidents-in-arizona/",
        "https://phxinjurylaw.com/blog/anatomy-of-a-fatal-bicycle-accident/",
        "https://phxinjurylaw.com/blog/dui-law-civil-vs-criminal-court/",
        "https://phxinjurylaw.com/blog/tips-on-handling-own-auto-accident-claim/",
        "https://phxinjurylaw.com/blog/all-car-accident-injuries-are-not-the-same/",
        "https://phxinjurylaw.com/blog/commercial-truck-accidents/",
        "https://phxinjurylaw.com/blog/financial-aftermath-of-a-dui/",
        "https://phxinjurylaw.com/blog/whos-at-fault-in-an-auto-accident/",
        "https://phxinjurylaw.com/blog/highway-accident-arizona-information-center/",
        "https://phxinjurylaw.com/blog/why-you-need-an-auto-accident-doctor/",
        "https://phxinjurylaw.com/blog/tbi-after-car-accident-and-premature-death/",
        "https://phxinjurylaw.com/blog/rear-end-collision-settlement-in-arizona/",
        "https://phxinjurylaw.com/blog/wrongful-death-of-fetus-in-arizona/",
        "https://phxinjurylaw.com/blog/wrongful-death-pain-and-suffering/",
        "https://phxinjurylaw.com/blog/worst-arizona-vehicular-accident-2019/",
        "https://phxinjurylaw.com/blog/auto-accident-claim-tips/",
        "https://phxinjurylaw.com/blog/left-hand-turn-accident-dui/",
        "https://phxinjurylaw.com/blog/head-and-back-injuries-in-dui-auto-accident/",
        "https://phxinjurylaw.com/blog/rear-end-accident-at-an-intersection/",
        "https://phxinjurylaw.com/blog/a-guide-to-personal-injury-in-arizona/",
        "https://phxinjurylaw.com/blog/dui-hit-and-run-incidents/",
        "https://phxinjurylaw.com/blog/freeway-rear-end-accidents/",
        "https://phxinjurylaw.com/blog/device-regulations-for-semi-trucks-safety/",
        "https://phxinjurylaw.com/blog/worst-arizona-vehicular-accidents-2014/",
        "https://phxinjurylaw.com/blog/neck-back-injury-in-highway-accident/",
        "https://phxinjurylaw.com/blog/liability-for-a-bicycle-accident-in-arizona/",
        "https://phxinjurylaw.com/blog/chronic-pain-and-brain-trauma-car-accidents/",
        "https://phxinjurylaw.com/blog/auto-accident-resulting-to-back-injury/",
        "https://phxinjurylaw.com/blog/truck-driver-accident-procedures/",
        "https://phxinjurylaw.com/blog/dealing-a-dui-repeat-offender-in-phoenix/",
        "https://phxinjurylaw.com/blog/the-right-compensation-for-your-accident/",
        "https://phxinjurylaw.com/blog/tips-on-considering-financial-losses/",
        "https://phxinjurylaw.com/blog/premature-death-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/deal-with-at-fault-drivers-insurance-company/",
        "https://phxinjurylaw.com/blog/back-spasms-and-back-pain-after-car-accident/",
        "https://phxinjurylaw.com/blog/distracted-driving-injury-awareness-month/",
        "https://phxinjurylaw.com/blog/dui-laws-in-arizona-explained/",
        "https://phxinjurylaw.com/blog/treatment-after-hit-and-run-accidents/",
        "https://phxinjurylaw.com/blog/hit-and-run-in-arizona/",
        "https://phxinjurylaw.com/blog/hit-and-run-at-a-stop-sign/",
        "https://phxinjurylaw.com/blog/victims-of-dui-accident-settlements/",
        "https://phxinjurylaw.com/blog/regulating-map-apps-in-arizona/",
        "https://phxinjurylaw.com/blog/manufacturing-car-defects-and-accidents/",
        "https://phxinjurylaw.com/blog/commercial-vehicle-accidents/",
        "https://phxinjurylaw.com/blog/truth-about-trucker-safety/",
        "https://phxinjurylaw.com/blog/back-injuries-after-a-rear-end-collision/",
        "https://phxinjurylaw.com/blog/personal-injury-claim-in-arizona/",
        "https://phxinjurylaw.com/blog/life-after-a-car-accident/",
        "https://phxinjurylaw.com/blog/rear-end-auto-accident-injuries/",
        "https://phxinjurylaw.com/blog/court-testimony-dui-car-accidents-victims/",
        "https://phxinjurylaw.com/blog/hit-and-run-pedestrian-accidents/",
        "https://phxinjurylaw.com/blog/how-long-to-file-a-personal-injury-lawsuit/",
        "https://phxinjurylaw.com/blog/can-you-get-ptsd-from-a-car-accident/",
        "https://phxinjurylaw.com/blog/arm-injury-after-an-auto-accident/",
        "https://phxinjurylaw.com/blog/top-30-dui-faqs-on-dui-cases/",
        "https://phxinjurylaw.com/blog/drowsy-driving/",
        "https://phxinjurylaw.com/blog/dui-accident-article-hub/",
        "https://phxinjurylaw.com/blog/fatal-drunk-driving/",
        "https://phxinjurylaw.com/blog/wrongful-death-of-an-unborn-child-fetus/",
        "https://phxinjurylaw.com/blog/best-arizona-injury-attorneys/",
        "https://phxinjurylaw.com/blog/rear-end-accidents-at-high-speed/",
        "https://phxinjurylaw.com/blog/file-a-nursing-home-abuse-complaint/",
    ],

    // Output directories (relative to project root)
    OUTPUT: {
        CONTENT_DIR: "./downloads/content",
        IMAGES_DIR: "./downloads/images",
    },

    // Image settings
    IMAGE_EXTRACTION: {
        // Path prefix for rewritten image URLs in markdown
        relativePath: "/assets/images/blog/",
        // Filename pattern: {slug} and {index} are replaced
        filenamePattern: "{slug}-{index}",
        // Optional: filter function to skip certain URLs (return false to skip)
        filter: (url) => true,

        // Featured image - set to null to disable
        // Extracted separately, falls back to first body image if not found
        featuredImage: {
            // CSS selector to find the featured image element
            selector: ".pageRow",
            // Function to extract the image URL from the element
            getValue: (el) => el.style.backgroundImage.replace(/url\(['"]?/, '').replace(/['"]?\)/, ''),
            // Optional: use a different element for alt text
            altSelector: ".vcex-page-title__text",
            getAlt: (el) => el?.textContent?.trim() || '',
            // Filename pattern: {slug} is replaced
            filenamePattern: "{slug}",
            // Frontmatter field names for the image
            frontmatterKey: "image",
            altFrontmatterKey: "imageAlt",
        },
    },

    // Frontmatter & content data
    // - Keys become lowercase frontmatter field names (underscores removed)
    // - String values are used directly as static values
    // - Objects with selector/getValue extract data from the page
    // - isContent: true → used as markdown body instead of frontmatter
    DATA: {
        // Example: Static value (same for all posts)
        AUTHOR: "Phoenix Accident and Injury Law Firm",

        // Example: Extract from an element
        TITLE: {
            selector: "title",
            getValue: (el) => el.textContent.trim(),
        },

        // Example: Extract from a meta tag
        DESCRIPTION: {
            selector: "meta[name='description']",
            getValue: (el) => el.getAttribute("content"),
        },

        // Example: Extract and format a date
        DATE: {
            selector: "meta[property='article:published_time']",
            getValue: (el) => el.getAttribute("content"),
        },

        // Example: Static category
        CATEGORY: "Blog",

        // Extract slug/path from URL (remove /blog/ prefix and leading slash)
        URL: {
            fromUrl: true,
            getValue: (url) => {
                const urlObj = new URL(url);
                const pathname = urlObj.pathname;
                // Remove /blog/ and get everything after it
                const blogIndex = pathname.indexOf('/blog/');
                if (blogIndex !== -1) {
                    return pathname.substring(blogIndex + '/blog/'.length).replace(/\/$/, ''); // Remove /blog/ prefix and trailing slash
                }
                return pathname.replace(/^\/|\/$/g, ''); // Fallback: return full path without slashes if /blog/ not found
            },
        },

        // The main content - must have isContent: true
        BODY: {
            selector: ".mainContentWrapper",
            getValue: (el) => el.innerHTML,
            isContent: true,
            // Optional: prepend markdown heading from this selector
            prependMarkdown: {
                selector: ".vcex-page-title__text",
                format: (text) => `# ${text}\n\n`,
            },
        },
    }
}
